version: '3.8'

services:
  api:
    # image: madurar/staticpcd-api
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on: 
      - db
    environment:
    #  DATABASE_URL: postgres://user:password@postgres:5432/staticpcd_controlroom
      PORT: 4000
    ports:
      - "8080:3000"
  
  db:
    image: postgres:13-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: Belpostgre123
      restart: always
      POSTGRES_DB: staticpcd_controlroom
